canvas-medical/canvas-plugins

- plugin_runner/plugin_runner.py
> Change the plugin runner to listen on 127.0.0.1 instead of [::]

- .github/actions/install-python-and-poetry/action.yml
- .github/actions/set-sha/action.yml
- .github/workflows/build-and-test.yml
- .github/workflows/pre-commit-auto-update-base.yml
- .github/workflows/pre-commit-auto-update.yml
- .github/workflows/pre-commit.yml
This PR fixes the gh actions. I gave up trying to figure out how to give this repo access to the workflows repo, so i just removed any references to the actions/workflows in that repo and made everything custom in here.
> Fix gh actions

- plugin_runner/plugin_runner.py
The `compute` method on Protocols runs in an async context, but authors of that method may not realize that. Given that, developers could very easily block the main thread by doing normal things like using the `requests` package to send HTTP requests.
This change makes user-defined code run in a thread from the default executor threadpool.
Note that this does not cause protocols to run in parallel — a future PR will address this after we get an idea for what if any limitations to set for parallel execution, for example max threads per event.
> Run Protocol compute method in a threadpool to avoid blocking the main event loop

- README.md
- canvas_cli/apps/logs/logs.py
- canvas_cli/apps/plugin/plugin.py
- canvas_cli/conftest.py
- canvas_cli/main.py
- canvas_cli/utils/context/context.py
- canvas_cli/utils/print/print.py
- logger/logger.py
- plugin_runner/plugin_runner.py
- plugin_runner/plugin_synchronizer.py
- plugin_runner/sandbox.py
- pyproject.toml
- Canvas CLI output is now a bit more human-friendly
- Added canvas_sdk modules to the sandbox allowlist
- Plugin load/reload exceptions should be captured and logged out, should not cause the process to crash
> Fixes from feedback during live demo

- README.md
- canvas_cli/apps/plugin/__init__.py
- canvas_cli/apps/plugin/plugin.py
- canvas_cli/main.py
there were some minor changes i had to make to home-app: https://github.com/canvas-medical/canvas/pull/16226
> Create enable and disable cli methods

- canvas_sdk/v1/data/lab.py
- canvas_sdk/v1/data/user.py
https://canvasmedical.atlassian.net/browse/KOALA-1843
> Adds LabReport, LabValue and related models.

- canvas_sdk/utils/db.py
- settings.py
https://canvasmedical.atlassian.net/browse/KOALA-2047
> Adds database parsing and addition to settings.

- .github/workflows/publish-and-release.yml
- pyproject.toml
[KOALA-2057](https://canvasmedical.atlassian.net/browse/KOALA-2057)
[KOALA-2057]: https://canvasmedical.atlassian.net/browse/KOALA-2057?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(ci): add automated releases using semantic release

- .github/workflows/publish-and-release.yml
> chore: fix semantic release

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
> chore(docs): add CONTRIBUTING.md and CODE_OF_CONDUCT.md

- .github/workflows/publish-and-release.yml
> chore: fix semantic release workflow

- .github/workflows/pre-commit.yml
> chore(ci): fix pre-commit on CI

- .pre-commit-config.yaml
Update pre-commit hooks to latest version
> chore: auto-update pre-commit hooks

- .github/workflows/publish-and-release.yml
> chore: enhance release process by installing and executing the distribution

- .github/workflows/publish-and-release.yml
> chore: fix test distribution step on semantic release gh action

- canvas_sdk/v1/data/base.py
> fix: valueSet query

- plugin_runner/plugin_runner.py
Implementing a style change Chris suggested
> style: use pathlib to construct a path

- canvas_sdk/effects/protocol_card/protocol_card.py
- canvas_sdk/effects/protocol_card/tests.py
- canvas_sdk/protocols/base.py
- canvas_sdk/protocols/clinical_quality_measure.py
- canvas_sdk/protocols/timeframe.py
- canvas_sdk/v1/data/__init__.py
- canvas_sdk/v1/data/base.py
- canvas_sdk/v1/data/billing.py
- canvas_sdk/v1/data/note.py
- canvas_sdk/v1/data/patient.py
- canvas_sdk/value_set/custom.py
- canvas_sdk/value_set/value_set.py
https://canvasmedical.atlassian.net/browse/KOALA-2101
This PR adds the functionality on the canvas-plugins side to convert the HCC Annual Wellness Visit protocol to a plugin. The corresponding home-app PR is here - https://github.com/canvas-medical/canvas/pull/16910
> feat: adds functionality for the hcc annual wellness visit protocol to be a plugin

- canvas_cli/apps/emit/emit.py
- canvas_cli/apps/logs/logs.py
- canvas_cli/apps/plugin/plugin.py
- canvas_cli/templates/plugins/default/{{ cookiecutter.__project_slug }}/protocols/my_protocol.py
- canvas_cli/tests.py
- canvas_cli/utils/context/context.py
- canvas_cli/utils/context/tests.py
- canvas_cli/utils/print/print.py
- canvas_cli/utils/print/tests.py
- canvas_sdk/base.py
- canvas_sdk/commands/base.py
- canvas_sdk/commands/tests/protocol/tests.py
- canvas_sdk/commands/tests/test_utils.py
- canvas_sdk/commands/tests/unit/tests.py
- canvas_sdk/data/client.py
- canvas_sdk/effects/banner_alert/tests.py
- canvas_sdk/effects/protocol_card/protocol_card.py
- canvas_sdk/effects/protocol_card/tests.py
- canvas_sdk/utils/http.py
- canvas_sdk/v1/data/patient.py
- canvas_sdk/v1/data/questionnaire.py
- canvas_sdk/value_set/tests/test_value_sets.py
- canvas_sdk/value_set/v2022/intervention.py
- canvas_sdk/value_set/value_set.py
- plugin_runner/plugin_runner.py
- plugin_runner/sandbox.py
- poetry.lock
- pyproject.toml
- test-plugins/my_first_plugin/protocols/protocol.py
[KOALA-2225](https://canvasmedical.atlassian.net/browse/KOALA-2225)
[KOALA-2225]: https://canvasmedical.atlassian.net/browse/KOALA-2225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: improve mypy configuration and fix the resulting errors

- canvas_sdk/protocols/clinical_quality_measure.py
https://canvasmedical.atlassian.net/browse/KOALA-2202
> feat: add is_predictive property to cqm class meta

- canvas_sdk/v1/data/common.py
- canvas_sdk/v1/data/imaging.py
https://canvasmedical.atlassian.net/browse/KOALA-1982
> feat: adds imaging models

- canvas_sdk/effects/patient_chart_summary_configuration.py
https://canvasmedical.atlassian.net/browse/KOALA-2208
Add coding gaps section to PatientChartConfiguration effect
> feat: add coding gaps to patient chart configuration effect

- canvas_sdk/base.py
- canvas_sdk/effects/banner_alert/add_banner_alert.py
- canvas_sdk/effects/banner_alert/remove_banner_alert.py
- canvas_sdk/effects/banner_alert/tests.py
- canvas_sdk/effects/base.py
- canvas_sdk/effects/protocol_card/protocol_card.py
- canvas_sdk/effects/protocol_card/tests.py
this PR adds `patient_filter` as a property on the BaseEffect class, and allows to users to pass in either a `patient_filter` or `patient_id` to apply the effect to. https://canvasmedical.atlassian.net/browse/KOALA-2198
> feat: add patient_filter to base effect's payload

- canvas_sdk/v1/data/protocol_override.py
Fixing a copy-paste error that I introduced in a previous PR.
> fix: related name for ProtocolOverride

- canvas_sdk/commands/base.py
- canvas_sdk/v1/data/base.py
- canvas_sdk/v1/data/condition.py
- canvas_sdk/v1/data/patient.py
- plugin_runner/sandbox.py
- poetry.lock
- pyproject.toml
@aduane I included rapidfuzz to enable plugins to perform fuzzy matching.
Useful for https://github.com/canvas-medical/nabla-ai-parser
It depends on https://github.com/canvas-medical/canvas/pull/16947
> feat: add line_number option when originating command

- poetry.lock
- pyproject.toml
> fix: remove a warning that happens at install time

- canvas_sdk/effects/patient_profile_configuration.py
> fix: typeddict import on patient configuration effect

- canvas_cli/apps/plugin/plugin.py
Reverts canvas-medical/canvas-plugins#241
> [feat] revert "fix: improve error handling for canvas_cli install command"

- canvas_sdk/handlers/base.py
> fix: deprecation warning message for BaseHandler event target

- settings.py
> fix: provide a default for CUSTOMER_IDENTIFIER

- canvas_sdk/v1/data/__init__.py
- canvas_sdk/v1/data/appointment.py
https://canvasmedical.atlassian.net/browse/KOALA-1991
https://canvasmedical.atlassian.net/browse/KOALA-1991
> feat: add appointment to data module

- canvas_sdk/v1/data/note.py
https://canvasmedical.atlassian.net/browse/KOALA-2214
> fix: add missing properties to note type

- canvas_sdk/v1/data/command.py
- canvas_sdk/v1/data/note.py
https://canvasmedical.atlassian.net/browse/KOALA-2385
> feat: change the Command model to use a foreign key to Note

- .github/workflows/build-and-test.yml
- canvas_sdk/commands/tests/protocol/tests.py
- canvas_sdk/commands/tests/test_utils.py
- canvas_sdk/effects/banner_alert/tests.py
[KOALA-2465](https://canvasmedical.atlassian.net/browse/KOALA-2465)
This PR needs https://github.com/canvas-medical/canvas/pull/17182 to be released 1st
[KOALA-2465]: https://canvasmedical.atlassian.net/browse/KOALA-2465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: proper fix integration tests

- canvas_cli/apps/plugin/plugin.py
[KOALA-2396](https://canvasmedical.atlassian.net/browse/KOALA-2396)
Depends on: https://github.com/canvas-medical/canvas/pull/17079
[KOALA-2396]: https://canvasmedical.atlassian.net/browse/KOALA-2396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add force option when uninstalling a plugin

- canvas_sdk/commands/commands/reason_for_visit.py
- canvas_sdk/commands/tests/test_utils.py
- canvas_sdk/commands/tests/unit/tests.py
- canvas_sdk/v1/data/__init__.py
- canvas_sdk/v1/data/reason_for_visit.py
https://canvasmedical.atlassian.net/browse/KOALA-2476
> feat: implement reason for visit codings with validations for rfv command

- canvas_sdk/commands/commands/reason_for_visit.py
[KOALA-2476](https://canvasmedical.atlassian.net/browse/KOALA-2476)
[KOALA-2476]: https://canvasmedical.atlassian.net/browse/KOALA-2476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: accept UUID type for rfv coding field

- canvas_sdk/effects/launch_modal.py
https://canvasmedical.atlassian.net/browse/KOALA-2546
- add target `RIGHT_CHART_PANE_LARGE` to LaunchModalEffect
> feat: add new target option to LaunchModalEffect

- canvas_sdk/commands/commands/lab_order.py
- canvas_sdk/v1/data/lab.py
https://canvasmedical.atlassian.net/browse/KOALA-2475
> feat: add partner lab models and update lab order command to validate results

- canvas_sdk/commands/base.py
- canvas_sdk/commands/commands/allergy.py
- canvas_sdk/commands/commands/assess.py
- canvas_sdk/commands/commands/close_goal.py
- canvas_sdk/commands/commands/diagnose.py
- canvas_sdk/commands/commands/family_history.py
- canvas_sdk/commands/commands/goal.py
- canvas_sdk/commands/commands/history_present_illness.py
- canvas_sdk/commands/commands/instruct.py
- canvas_sdk/commands/commands/lab_order.py
- canvas_sdk/commands/commands/medical_history.py
- canvas_sdk/commands/commands/medication_statement.py
- canvas_sdk/commands/commands/past_surgical_history.py
- canvas_sdk/commands/commands/perform.py
- canvas_sdk/commands/commands/plan.py
- canvas_sdk/commands/commands/prescribe.py
- canvas_sdk/commands/commands/questionnaire.py
- canvas_sdk/commands/commands/reason_for_visit.py
- canvas_sdk/commands/commands/remove_allergy.py
- canvas_sdk/commands/commands/stop_medication.py
- canvas_sdk/commands/commands/task.py
- canvas_sdk/commands/commands/update_diagnosis.py
- canvas_sdk/commands/commands/update_goal.py
- canvas_sdk/commands/commands/vitals.py
- canvas_sdk/commands/tests/test_base_command.py
https://canvasmedical.atlassian.net/browse/KOALA-2561
> fix: refactor command values into dynamic method

- canvas_sdk/commands/commands/lab_order.py
> fix: lab order command validations

- canvas_sdk/commands/commands/lab_order.py
[KOALA-2590](https://canvasmedical.atlassian.net/browse/KOALA-2590)
Fixes https://github.com/canvas-medical/canvas-plugins/issues/427
[KOALA-2590]: https://canvasmedical.atlassian.net/browse/KOALA-2590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: allow setting lab partner by name or as None

- canvas_sdk/commands/commands/instruct.py
- canvas_sdk/commands/constants.py
[KOALA-2480](https://canvasmedical.atlassian.net/browse/KOALA-2480)
[KOALA-2480]: https://canvasmedical.atlassian.net/browse/KOALA-2480?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add instruct command

- canvas_sdk/commands/__init__.py
> fix: add missing commands to module init

- canvas_sdk/commands/tests/protocol/tests.py
- canvas_sdk/commands/tests/test_utils.py
- canvas_sdk/effects/banner_alert/tests.py
- plugin_runner/installation.py
- plugin_runner/plugin_runner.py
- **fix double logging**
- **fix linter warning**
- **reconnect if connection is closed in HandleEvent**
> fix: reconnect to database when connection is lost

- canvas_sdk/v1/data/__init__.py
- canvas_sdk/v1/data/staff.py
https://canvasmedical.atlassian.net/browse/KOALA-2632
This PR adds a `StaffContactPoint` data module model so that Staff contact points (phone, email, etc.) are available in the plugins data module. 
Corresponding home-app PR is here - https://github.com/canvas-medical/canvas/pull/17327
> feat: adds a StaffContactPoint data module model

- plugin_runner/sandbox.py
This allows developers to create and decode signed JWTs
> feat: allow importing jwt in the plugin runner sandbox

- canvas_sdk/v1/data/lab.py
uncomment ordering_provider since staff model is live
https://github.com/canvas-medical/canvas-plugins/discussions/471
> feat: uncomment ordering_provider

- canvas_sdk/commands/commands/perform.py
> fix: allow originating perform without data

- canvas_sdk/effects/show_button.py
- canvas_sdk/handlers/action_button.py
https://canvasmedical.atlassian.net/browse/KOALA-2681
documentation: https://github.com/canvas-medical/documentation/pull/545
> feat: add priority to action buttons

- canvas_cli/apps/emit/event_fixtures/SIMPLE_API_REQUEST.ndjson
- canvas_sdk/effects/simple_api.py
- canvas_sdk/handlers/simple_api/api.py
- canvas_sdk/tests/handlers/test_simple_api.py
- plugin_runner/plugin_runner.py
https://canvasmedical.atlassian.net/browse/KOALA-2649
Documentation PR: https://github.com/canvas-medical/documentation/pull/540
Added support for path patterns.
This allows developers to define path parameters in their routes, and extract the values when handling:
```python
@api.get("/path/<id>")
def route(self):
id_ = self.request.path_params["id"]
...
```
> feat: match SimpleAPI URLs with path patterns

- canvas_sdk/effects/protocol_card/protocol_card.py
https://github.com/canvas-medical/canvas-plugins/issues/445
Add all available ProtocolCard [statuses](https://github.com/canvas-medical/canvas/blob/96315e64fbfc459344a32808e936a98975ddd23d/home-app/api/models/common.py#L257)
> feat: add all protocol card statuses

- canvas_sdk/effects/patient_profile_configuration.py
https://canvasmedical.atlassian.net/browse/KOALA-1969
> feat: add portal section to patient profile configuration

- canvas_sdk/commands/commands/questionnaire/__init__.py
[KOALA-2787](https://canvasmedical.atlassian.net/browse/KOALA-2787)
resolves: https://github.com/canvas-medical/canvas-plugins/issues/467
[KOALA-2787]: https://canvasmedical.atlassian.net/browse/KOALA-2787?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: remove duplicate question append

- canvas_sdk/tests/commands/test_commands.py
> chore(tests): increase wait time for plugin installation

- plugin_runner/sandbox.py
https://canvasmedical.atlassian.net/browse/KOALA-2841
Addresses https://github.com/canvas-medical/canvas-plugins/discussions/584
> feat: allow importing ZoneInfo

- canvas_sdk/v1/data/__init__.py
- canvas_sdk/v1/data/message.py
Internal tracking: [KOALA-2801](https://canvasmedical.atlassian.net/browse/KOALA-2801)
[KOALA-2801]: https://canvasmedical.atlassian.net/browse/KOALA-2801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add message to data module

- plugin_runner/plugin_runner.py
> fix: remove event_handler_count to keep influx from exploding

- canvas_sdk/value_set/custom.py
- canvas_sdk/value_set/v2022/allergy.py
- canvas_sdk/value_set/v2022/assessment.py
- canvas_sdk/value_set/v2022/communication.py
- canvas_sdk/value_set/v2022/condition.py
- canvas_sdk/value_set/v2022/device.py
- canvas_sdk/value_set/v2022/diagnostic_study.py
- canvas_sdk/value_set/v2022/encounter.py
- canvas_sdk/value_set/v2022/immunization.py
- canvas_sdk/value_set/v2022/individual_characteristic.py
- canvas_sdk/value_set/v2022/intervention.py
- canvas_sdk/value_set/v2022/laboratory_test.py
- canvas_sdk/value_set/v2022/medication.py
- canvas_sdk/value_set/v2022/physical_exam.py
- canvas_sdk/value_set/v2022/procedure.py
https://canvasmedical.atlassian.net/browse/KOALA-2859
> fix: don't copy locals(), prevents additional memory usage

- canvas_cli/utils/validators/manifest_schema.py
- canvas_sdk/effects/launch_modal.py
https://canvasmedical.atlassian.net/browse/KOALA-2798
> feat: launch modal effect improvements

- plugin_runner/sandbox.py
> allow defaultdict and Counter

- canvas_sdk/handlers/base.py
This PR resolves https://github.com/canvas-medical/canvas-plugins/issues/649
> feat: export installed SDK version

- example-plugins/patient_portal_search_appointments_slots_plugin/CANVAS_MANIFEST.json
- example-plugins/patient_portal_search_appointments_slots_plugin/README.md
- example-plugins/patient_portal_search_appointments_slots_plugin/handlers/search_appointments_slots_handler.py
feat: filter not available providers in appointments search form
[KOALA-2986](https://canvasmedical.atlassian.net/browse/KOALA-2986)
[KOALA-2986]: https://canvasmedical.atlassian.net/browse/KOALA-2986?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: filter not available providers in appointments search form

- canvas_sdk/tests/data/test_utils.py
- canvas_sdk/v1/data/__init__.py
- canvas_sdk/v1/data/allergy_intolerance.py
- canvas_sdk/v1/data/assessment.py
- canvas_sdk/v1/data/billing.py
- canvas_sdk/v1/data/claim.py
- canvas_sdk/v1/data/claim_line_item.py
- canvas_sdk/v1/data/command.py
- canvas_sdk/v1/data/condition.py
- canvas_sdk/v1/data/detected_issue.py
- canvas_sdk/v1/data/device.py
- canvas_sdk/v1/data/discount.py
- canvas_sdk/v1/data/fields.py
- canvas_sdk/v1/data/imaging.py
- canvas_sdk/v1/data/invoice.py
- canvas_sdk/v1/data/lab.py
- canvas_sdk/v1/data/line_item_transaction.py
- canvas_sdk/v1/data/medication.py
- canvas_sdk/v1/data/observation.py
- canvas_sdk/v1/data/organization.py
- canvas_sdk/v1/data/payment_collection.py
- canvas_sdk/v1/data/posting.py
- canvas_sdk/v1/data/protocol_override.py
- canvas_sdk/v1/data/questionnaire.py
- canvas_sdk/v1/data/utils.py
[KOALA-2878](https://canvasmedical.atlassian.net/browse/KOALA-2878)
[KOALA-2879](https://canvasmedical.atlassian.net/browse/KOALA-2879)
[KOALA-2878]: https://canvasmedical.atlassian.net/browse/KOALA-2878?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[KOALA-2879]: https://canvasmedical.atlassian.net/browse/KOALA-2879?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Depends on: https://github.com/canvas-medical/canvas/pull/17675
> feat: add claim and associated data modules

- canvas_sdk/utils/http.py
Internal tracking: [KOALA-3019](https://canvasmedical.atlassian.net/browse/KOALA-3019)
This pull request includes a small change to the `PharmacyHttp` class in `canvas_sdk/utils/http.py`. The change updates the environment variable name and default value for the pharmacy service endpoint.
[KOALA-3019]: https://canvasmedical.atlassian.net/browse/KOALA-3019?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: env var and default url for pharmacy service

- canvas_sdk/utils/http.py
This pull request makes a single change to the `canvas_sdk/utils/http.py` file. The change disables SSL verification for the HTTP client session by setting `self._http_client._session.verify` to `False`.
> fix: remove cert validation from pharmacy

- plugin_runner/sandbox.py
closes https://github.com/canvas-medical/canvas-plugins/discussions/762
> feat: add additional allowed imports for abc and typing

- canvas_cli/apps/plugin/plugin.py
- canvas_cli/apps/plugin/tests.py
- canvas_cli/utils/validators/manifest_schema.py
- pyproject.toml
- uv.lock
Closes https://github.com/canvas-medical/canvas-plugins/issues/772
Add ability to exclude files when packaging/building using new `build_ignore_patterns` property in `CANVAS_MANIFEST.json`
Internal Tracking - https://canvasmedical.atlassian.net/browse/TINA-605
Docs PR - https://github.com/canvas-medical/documentation/pull/671
> feat: add ability to ignore files when packaging

- plugin_runner/allowed-module-imports.json
> fix: immunization statement allowed_imports

- plugin_runner/sandbox.py
for https://github.com/canvas-medical/canvas-plugins/discussions/855
> feat: add Union to allowed import list

- plugin_runner/sandbox.py
request from https://github.com/canvas-medical/canvas-plugins/discussions/869#discussioncomment-14036416
https://canvasmedical.atlassian.net/browse/KOALA-3177
https://docs.pydantic.dev/latest/api/root_model/
> feat: add pydantic.RootModel to sandbox

- canvas_cli/utils/validators/manifest_schema.py
https://canvasmedical.atlassian.net/browse/KOALA-3040
> fix: add panel applications

- .github/actions/install-python-and-uv/action.yml
- .pre-commit-config.yaml
- pyproject.toml
- uv.lock
> chore(deps): update dev dependencies

- pyproject.toml
> fix(cli): include plugin template test package

- example-plugins/example_patient_portal_page/README.md
Added an image of the patient portal with application and widgets.
> chore: add image to example patient portal plugin

- example-plugins/recurring_appointments/CANVAS_MANIFEST.json
- example-plugins/recurring_appointments/README.md
- example-plugins/recurring_appointments/cron/banner_alert.py
- example-plugins/recurring_appointments/handlers/form.py
- example-plugins/recurring_appointments/handlers/recurrence.py
- example-plugins/recurring_appointments/utils/constants.py
https://canvasmedical.atlassian.net/browse/KOALA-3377
> chore(docs): add ends after and recurrence interval field to recurrence example plugin

- canvas_sdk/test_utils/factories/__init__.py
- canvas_sdk/test_utils/factories/medication_history.py
- canvas_sdk/v1/data/__init__.py
- canvas_sdk/v1/data/medication_history.py
- plugin_runner/allowed-module-imports.json
https://canvasmedical.atlassian.net/browse/KOALA-3334
Closes https://github.com/canvas-medical/canvas-plugins/issues/1002
Requires https://github.com/canvas-medical/canvas/pull/18095
Add Medication History related models
> feat: add medication history related models
