canvas_sdk/protocols/base.py, custom-plugins/my_first_plugin/protocols/protocol.py, custom-plugins/promote_kirkland_signature_drugs/protocols/protocol.py
Moves the __init__ method to the `BaseProtocol` class.
=> Moves __init__ to BaseProtocol class

canvas_cli/apps/auth/utils.py, canvas_cli/utils/validators/manifest_schema.py, custom-plugins/promote_kirkland_signature_drugs/CANVAS_MANIFEST.json
All this does is make it valid to have secrets in the manifest.
And also it allows the cli to work against a local canvas instance.
=> Plugins can declare secrets in the manifest

plugin_runner/plugin_runner.py
Removes old 'logger' statements.
=> Changes log statements.

canvas_sdk/protocols/base.py
Fixes https://github.com/canvas-medical/canvas-plugins/pull/54
- Sets target on protocol initialization
- Is permissive if there is no provided context
=> Fix protocol initialization issues

canvas_sdk/utils/stats.py, canvas_sdk/utils/timing.py, plugin_runner/plugin_runner.py
https://canvasmedical.atlassian.net/browse/KOALA-1516
=> Adds timing metrics for Protocol compute and Event response

.pre-commit-config.yaml, canvas_sdk/commands/base.py, canvas_sdk/commands/commands/assess.py, canvas_sdk/commands/commands/diagnose.py, canvas_sdk/commands/commands/goal.py, canvas_sdk/commands/commands/history_present_illness.py, canvas_sdk/commands/commands/medication_statement.py, canvas_sdk/commands/commands/plan.py, canvas_sdk/commands/commands/prescribe.py, canvas_sdk/commands/commands/questionnaire.py, canvas_sdk/commands/commands/reason_for_visit.py, canvas_sdk/commands/commands/stop_medication.py, canvas_sdk/commands/commands/update_goal.py, canvas_sdk/commands/tests/test_utils.py, canvas_sdk/commands/tests/tests.py
second attempt at this one: [Validate command classes on demand and not on init](https://github.com/canvas-medical/canvas-plugins/pull/67). 
this time around we made every field optional, so that there are no validation errors on init for empty values. 
and then for each type of effect, we have a custom validation based on the fields that we indicate are required for that type of effect. 
note: tests will fail spectacularly, but i will address tonight/tomorrow
=> Validate command classes on demand, with specific validation for each type of effect

plugin_runner/plugin_runner.py
We already skip plugins that fail to load due to an ImportError, this change increases the types of errors that would skip a plugin considerably. It is extremely important to prevent the process from crashing on load, as circus will immediately attempt to resurrect it, causing a bootloop.
=> Prevent bootlooping due to a failed plugin load.

canvas_sdk/commands/tests/test_utils.py, canvas_sdk/commands/tests/tests.py, logger/logger.py
This will help separate log messages between containers in multi-container deployments.
=> Prepend the hostname to log lines if the hostname is defined in the env

canvas_cli/apps/plugin/plugin.py
Reagan noticed that enable/disable from the cli was returning non-zero exit codes. that's because we were looking for the wrong code on response (aka not `ok`). this pr fixes that.  
here is what enable/disable look like from the cli now:
=> for enable/disable check for status ok to give success message

canvas_sdk/commands/tests/test_utils.py, canvas_sdk/effects/banner_alert/add_banner_alert.py, canvas_sdk/effects/banner_alert/remove_banner_alert.py, canvas_sdk/effects/banner_alert/tests.py
While creating the ProtocolCard effect, I leveraged the canvas_sdk base class that has validation before effects are applied. I realized that banner alerts weren't using that class yet, so this pr makes that change! it makes the experience very nice because instantiating the class does not require any specific params.
=> Make banner alert effects have all optional params and validate on apply

canvas_cli/apps/plugin/plugin.py, canvas_cli/apps/plugin/tests.py, canvas_cli/utils/validators/manifest_schema.py, canvas_sdk/protocols/clinical_quality_measure.py
https://canvasmedical.atlassian.net/browse/KOALA-1858
This PR creates the base class for ClinicalQualityMeasures that will be uploaded via plugins. It is a subclass of the Protocol class and adds the necessary meta properties that will be used in home-app. 
In order to get these meta properties over to home-app, i decided to edit the manifest file to include the cqm properties for any protocols that use this base class. this file editing only happens if what's in the meanifest file does not match what's in the protocol. that way the developer does not need to worry about keeping them in sync. 
still to do:
=> Create CQM protocol subclass 

.github/workflows/publish-and-release.yml
=> chore: fix semantic-release publish

pyproject.toml
The canvas-cli is erroring out when using because of not finding the settings file. When instantiating a command (i.e. `canvas init`), the following error is thrown:
```
ModuleNotFoundError: No module named 'settings'
```
This PR adds the settings file to `pyproject.toml` so that it can be found and referenced in the Django setup process.
=> fix: fix settings error in canvas-cli

canvas_cli/apps/plugin/plugin.py
Reagan reported that installing plugins doesn't work when the protocol file imports certain libraries. this is because we were previously using `importlib` to fully import those files to pull out the meta properties before install. This PR changes the mechanism for pulling out that info (using `ast`) so that we don't need to import! 
slack thread with context: https://canvas-medical.slack.com/archives/C055B74UKJP/p1729204957000159?thread_ts=1729196011.314639&cid=C055B74UKJP
=> fix: pull out meta properties of CQM protocols without importing file

canvas_cli/templates/plugins/default/{{ cookiecutter.__project_slug }}/protocols/my_protocol.py, plugin_runner/authentication.py, plugin_runner/plugin_runner.py, plugin_runner/sandbox.py, plugin_runner/tests/fixtures/plugins/example_plugin/CANVAS_MANIFEST.json, plugin_runner/tests/fixtures/plugins/example_plugin/README.md, plugin_runner/tests/fixtures/plugins/example_plugin/protocols/my_protocol.py, plugin_runner/tests/fixtures/plugins/test_module_imports_outside_plugin_v1/CANVAS_MANIFEST.json, plugin_runner/tests/fixtures/plugins/test_module_imports_outside_plugin_v1/README.md, plugin_runner/tests/fixtures/plugins/test_module_imports_outside_plugin_v1/other_module/base.py, plugin_runner/tests/fixtures/plugins/test_module_imports_outside_plugin_v1/protocols/my_protocol.py, plugin_runner/tests/fixtures/plugins/test_module_imports_outside_plugin_v2/CANVAS_MANIFEST.json, plugin_runner/tests/fixtures/plugins/test_module_imports_outside_plugin_v2/README.md, plugin_runner/tests/fixtures/plugins/test_module_imports_outside_plugin_v2/other_module/base.py, plugin_runner/tests/fixtures/plugins/test_module_imports_outside_plugin_v2/protocols/my_protocol.py, plugin_runner/tests/fixtures/plugins/test_module_imports_outside_plugin_v3/CANVAS_MANIFEST.json, plugin_runner/tests/fixtures/plugins/test_module_imports_outside_plugin_v3/README.md, plugin_runner/tests/fixtures/plugins/test_module_imports_outside_plugin_v3/other_module/base.py, plugin_runner/tests/fixtures/plugins/test_module_imports_outside_plugin_v3/protocols/my_protocol.py, plugin_runner/tests/fixtures/plugins/test_module_imports_plugin/CANVAS_MANIFEST.json, plugin_runner/tests/fixtures/plugins/test_module_imports_plugin/README.md, plugin_runner/tests/fixtures/plugins/test_module_imports_plugin/other_module/base.py, plugin_runner/tests/fixtures/plugins/test_module_imports_plugin/protocols/my_protocol.py, plugin_runner/tests/test_plugin_runner.py, plugin_runner/tests/test_sandbox.py, poetry.lock, pyproject.toml, settings.py
[KOALA-2189](https://canvasmedical.atlassian.net/browse/KOALA-2189)
This PR adds support for importing other modules within a plugin package.
This PR also replaces the use of `find_spec` from `importlib.util` with a safer approach because `find_spec` will implicitly import the parent module when the given name refers to a submodule. 
In particular, this behavior presents a security risk: if a bad actor manages to inject malicious code into the` __init__.py` file of the package, that code will execute as soon as the package is imported. Since `find_spec` will import the package to resolve submodules, any malicious code in `__init__.py` will run even before the sandbox has a chance to apply its restrictions.  cc @beaugunderson 
[KOALA-2189]: …
=> feat(plugins): add support for importing other modules within a plugin

plugin_runner/plugin_runner.py
=> fix: prevent plugin runner from exiting when loading a plugin with errors

canvas_sdk/v1/data/base.py, canvas_sdk/v1/data/condition.py
https://canvasmedical.atlassian.net/browse/KOALA-2288
This fixes an issue where `ValueSetLookupQuerySet` was changed to not inherit from `CommittableQuerySet` and the `committed` and `for_patient` methods were not available for use.
=> fix: fixes inheritance issue

canvas_cli/apps/plugin/plugin.py
[KOALA-2338](https://canvasmedical.atlassian.net/browse/KOALA-2338)
Depends on: https://github.com/canvas-medical/canvas/pull/17042
[KOALA-2338]: https://canvasmedical.atlassian.net/browse/KOALA-2338?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: improve error handling for canvas_cli install command

canvas_cli/apps/plugin/plugin.py
[KOALA-2338](https://canvasmedical.atlassian.net/browse/KOALA-2338)
Depends on: https://github.com/canvas-medical/canvas/pull/17042
[KOALA-2338]: https://canvasmedical.atlassian.net/browse/KOALA-2338?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: improve error handling for canvas_cli install

canvas_cli/templates/plugins/default/{{ cookiecutter.__project_slug }}/protocols/my_protocol.py, canvas_sdk/handlers/action_button.py, canvas_sdk/handlers/application.py, canvas_sdk/handlers/cron_task.py, canvas_sdk/protocols/clinical_quality_measure.py, plugin_runner/plugin_installer.py, plugin_runner/tests/test_application.py, plugin_runner/tests/test_plugin_installer.py, test-plugins/my_first_plugin/protocols/protocol.py
This PR fixes the following deprecation warnings:
1. `plugin_runner/tests/test_application.py`
```
PytestCollectionWarning: cannot collect test class 'TestApplication' because it has a __init__ constructor (from: plugin_runner/tests/test_application.py)
class TestApplication(Application):
```
2. `plugin_runner/tests/test_plugin_installer.py::test_plugin_installation_from_tarball`
```
DeprecationWarning: pathlib.Path.__enter__() is deprecated and scheduled for removal in Python 3.13; Path objects as a context manager is a no-op
with download_plugin(attributes["package"]) as plugin_file_path:
```
3. `plugin_runner/tests/test_application.py::test_compute_event_not_targeted`
```
DeprecatedWarning: target is deprecated as of 0.11.0 and will be removed in 1.0.0. Use 'event.target.id' directly …
```
=> chore: fix python warnings

plugin_runner/plugin_runner.py, plugin_runner/sandbox.py, plugin_runner/tests/fixtures/plugins/test_implicit_imports_plugin/CANVAS_MANIFEST.json, plugin_runner/tests/fixtures/plugins/test_implicit_imports_plugin/README.md, plugin_runner/tests/fixtures/plugins/test_implicit_imports_plugin/protocols/my_protocol.py, plugin_runner/tests/fixtures/plugins/test_implicit_imports_plugin/templates/__init__.py, plugin_runner/tests/fixtures/plugins/test_implicit_imports_plugin/templates/base.py, plugin_runner/tests/fixtures/plugins/test_implicit_imports_plugin/utils/__init__.py, plugin_runner/tests/fixtures/plugins/test_implicit_imports_plugin/utils/base.py, plugin_runner/tests/fixtures/plugins/test_module_forbidden_imports_plugin/CANVAS_MANIFEST.json, plugin_runner/tests/fixtures/plugins/test_module_forbidden_imports_plugin/README.md, plugin_runner/tests/fixtures/plugins/test_module_forbidden_imports_plugin/other_module/base.py, plugin_runner/tests/fixtures/plugins/test_module_forbidden_imports_plugin/protocols/my_protocol.py, plugin_runner/tests/fixtures/plugins/test_module_forbidden_imports_runtime_plugin/CANVAS_MANIFEST.json, plugin_runner/tests/fixtures/plugins/test_module_forbidden_imports_runtime_plugin/README.md, plugin_runner/tests/fixtures/plugins/test_module_forbidden_imports_runtime_plugin/other_module/base.py, plugin_runner/tests/fixtures/plugins/test_module_forbidden_imports_runtime_plugin/protocols/my_protocol.py, plugin_runner/tests/test_plugin_runner.py, plugin_runner/tests/test_sandbox.py
[KOALA-2422](https://canvasmedical.atlassian.net/browse/KOALA-2422)
This PR solves issues where dependent modules and implicit imports (e.g., `__init__.py` files) could be executed before being securely evaluated inside a sandbox. It also ensures the latest version of all modules is always loaded during execution. 
1. **Ensured Secure Evaluation of Dependent Modules:**  
- Modified the evaluation flow to ensure dependent modules (including `__init__.py` files) are evaluated securely inside the sandbox before being executed.  
- Prevented premature execution of dependent modules by deferring their evaluation until all implicit imports are properly handled.
-  Introduced recursive evaluation for implicit imports to ensure all modules in the package hierarchy are securely and consistently …
=> fix: reloading relative imports on plugin updates

canvas_sdk/commands/tests/test_utils.py, canvas_sdk/effects/banner_alert/tests.py
Tests should fail if HTTP requests core to the test fail.
=> test: use `raise_for_status()` when making http requests in integration tests

canvas_sdk/commands/tests/protocol/tests.py, canvas_sdk/commands/tests/test_utils.py, canvas_sdk/effects/banner_alert/tests.py
This PR solves the issue with the `canvas_sdk/effects/banner_alert/tests.py::test_protocol_that_adds_banner_alert` test. 
However, the `canvas_sdk/commands/tests/protocol/tests.py::test_protocol_that_inserts_every_command` integration test is still failing due to a regression introduced in version 1.146.0 of home-app. This regression broke the `updateGoal` interpreter, preventing that command type from being originated correctly.
**UPDATE: I'll ignore updateGoal command for now to unlock the release.**
=> chore: fix integration tests

canvas_sdk/v1/data/allergy_intolerance.py, canvas_sdk/v1/data/base.py, canvas_sdk/v1/data/billing.py, canvas_sdk/v1/data/condition.py, canvas_sdk/v1/data/lab.py, canvas_sdk/v1/data/medication.py, canvas_sdk/v1/data/observation.py, canvas_sdk/v1/data/protocol_override.py, canvas_sdk/v1/data/questionnaire.py
https://canvasmedical.atlassian.net/browse/KOALA-2464
=> feat: add mixins for CommittableQuerySet and PatientAssetQuerySet

.pre-commit-config.yaml
Update pre-commit hooks to latest version
=> chore: auto-update pre-commit hooks

canvas_cli/utils/validators/manifest_schema.py, canvas_sdk/questionnaires/__init__.py, canvas_sdk/questionnaires/tests/test_utils.py, canvas_sdk/questionnaires/utils.py, canvas_sdk/templates/utils.py, canvas_sdk/utils/plugins.py, canvas_sdk/v1/data/coverage.py, plugin_runner/sandbox.py, plugin_runner/tests/fixtures/plugins/test_load_questionnaire/CANVAS_MANIFEST.json, plugin_runner/tests/fixtures/plugins/test_load_questionnaire/README.md, plugin_runner/tests/fixtures/plugins/test_load_questionnaire/protocols/my_protocol.py, plugin_runner/tests/fixtures/plugins/test_load_questionnaire/questionnaires/example_questionnaire.yml, plugin_runner/tests/test_plugin_runner.py, schemas/questionnaire.json
[KOALA-2219](https://canvasmedical.atlassian.net/browse/KOALA-2219)
[KOALA-2219]: https://canvasmedical.atlassian.net/browse/KOALA-2219?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: install questionnaires via plugins

canvas_sdk/utils/stats.py, plugin_runner/plugin_runner.py
[KOALA-2564](https://canvasmedical.atlassian.net/browse/KOALA-2564)
This PR logs the number of event handlers per event whenever plugins are reloaded. This enables the ability to run queries like the following in Grafana:
```sql
SELECT event, customer, LAST(value) AS nr_handlers  FROM "plugins_event_nr_handlers" GROUP BY event, customer
```
| Time                | Event                                 | Customer | Nr. Handlers |
|---------------------|--------------------------------------|----------|--------------|
| 1739810042000000000 | PLAN_COMMAND__POST_INSERTED_INTO_NOTE | local    | 1            |
| 1739810042000000000 | VITAL_SIGN_UPDATED                   | local    | 0            |
[KOALA-2564]: https://canvasmedical.atlassian.net/browse/KOALA-2564?atlOrigin=eyJpIjoiNWRkNTljNzYxN …
=> chore(metrics): log nr event handlers

conftest.py
This PR addresses an issue where some tests were failing due to plugin modules not being found. After investigating, it seems that adding `PLUGINS_DIR` to the path before it exists was causing errors importing plugin modules. The fix ensures that PLUGINS_DIR exists before the tests are executed.
=> test: ensure PLUGINS_DIR exists before being added to sys.path

canvas_sdk/v1/data/__init__.py, canvas_sdk/v1/data/appointment.py
https://canvasmedical.atlassian.net/browse/KOALA-2633
This PR adds the `AppointmentExternalIdentifier` model to the Data Module. The use case for this is to make it possible to query appointments by their external identifier values (often needed in webhook and integrations functionality). 
Example usage:
```
appointments = Appointment.objects.filter(external_identifiers__value='bWNEvzC3pFfcKckLoA')
```
The corresponding home-app PR is here: https://github.com/canvas-medical/canvas/pull/17325
=> feat: adds AppointmentExternalIdentifier model to data module

canvas_sdk/handlers/simple_api/api.py
It's more appropriate for the SimpleAPI route registry to live at the class level rather than the instance level. The changes in this PR moves construction of the route registry to `__init_subclass__`.
=> refactor: moved construction of SimpleAPI route registry to __init_subclass__

canvas_sdk/handlers/simple_api/api.py, canvas_sdk/handlers/simple_api/tools.py, canvas_sdk/tests/handlers/test_simple_api.py
For consistency and user-interface purposes, having headers, query parameters, and form subparts represented as a "multidict" (i.e. a dict that can have multiple values per key) is a common approach.
Most of the time, developers would interact with these structures as if they were a regular Python dict, but developers that want to access additional values with a given key name would be able to.
This change is not backward compatible, and would require customer communication.
=> refactor: change SimpleAPI request headers and query parameters to be a multidict structure

canvas_sdk/v1/data/__init__.py, canvas_sdk/v1/data/banner_alert.py, canvas_sdk/v1/data/staff.py
Resolves https://canvasmedical.atlassian.net/browse/KOALA-2667
Depends on home-app PR: https://github.com/canvas-medical/canvas/pull/17420
Allows a plugin developer to look up which banner alerts have already been created. Likely useful when precomputing all banner alerts up front.
=> feat: add banner alerts to data module

canvas_sdk/handlers/simple_api/api.py, canvas_sdk/tests/handlers/test_simple_api.py, plugin_runner/plugin_runner.py
https://canvasmedical.atlassian.net/browse/KOALA-2742
Recent changes to SimpleAPI path parameters broke my SimpleAPI handler.
A simplified version of my handler:
```python
class CoolApp(SimpleAPI):
@api.get("/")
def index(self) -> list[Response | Effect]:
return [
HTMLResponse(
render_to_string("static/index.html"),
status_code=HTTPStatus.OK,
)
]
@api.get("/main.js")
def get_main_js(self) -> list[Response | Effect]:
return [
Response(
render_to_string("static/main.js").encode(),
status_code=HTTPStatus.OK,
content_type="text/javascript",
)
]
```
Before, requests to `GET /main.js` returned the javascript as expected, and `GET /` returned the html as expected.
After the change, requests to `GET /main.js` returned the html (and the `GET /` continued to return the html).
The changes in this PR …
=> fix: make path matching regex compatible with root paths ('/')

canvas_cli/utils/validators/manifest_schema.py
Depends on a future home-app release before these permissions are respected.
=> feat: allow iframes to request the camera permission

canvas_sdk/handlers/base.py, plugin_runner/plugin_runner.py
https://canvasmedical.atlassian.net/browse/KOALA-2741
Resolves https://github.com/canvas-medical/canvas-plugins/issues/290
Resolves https://github.com/canvas-medical/canvas-plugins/issues/503
This adds the ability to know which customer instance your code is executing on.
=> feat: add environment dict containing the customer identifier to plugin handler scope

logger/logger.py, plugin_runner/plugin_runner.py
https://canvasmedical.atlassian.net/browse/KOALA-2765
Blocking for Redis messages with no timeouts leads to situations where Redis disconnects but our code continues to block forever.
This PR updates our Redis `PSUBSCRIBE` consumer to wait for 5 seconds and then check the connection health so as to keep the Redis connection alive.
=> fix: don't block for Redis messages

canvas_sdk/handlers/simple_api/__init__.py, canvas_sdk/handlers/simple_api/security.py, canvas_sdk/tests/handlers/test_simple_api.py, canvas_sdk/v1/data/user.py
Relates to https://canvasmedical.atlassian.net/browse/KOALA-2706
Depends on https://github.com/canvas-medical/canvas/pull/17443
1. Add ability to protect SimpleAPI handlers based on a valid Canvas session.
2. Add email to the CanvasUser data model. (Unrelated, but I'm grouping it into these changes since it's tiny)
=> feat: add session based auth to simpleapi

canvas_sdk/utils/http.py, canvas_sdk/utils/tests.py
This is primarily to support Hyperscribe by adding the `status_code` to the result of `get_json`.
=> feat: add JsonOnlyResponse and a test for ontologies_http

plugin_runner/sandbox.py, plugin_runner/tests/test_sandbox.py
- **fixes for dictionary and list access as well as urllib.parse**
- **fix for determining node names**
tested by loading all plugins and diffing the output to ensure this didn't make things worse (the only changes were line numbers):
=> fix: un-break sandbox dictionary and list access

plugin_runner/plugin_runner.py
We were missing tags in Sentry because we weren't using the new sentry_sdk global_scope functionality. `plugin_runner` exceptions were getting the `plugin-name` tag but not the `source=plugin-runner` tag or the `customer` tag.
For example, this issue has the `plugin-name` but no `source` or `customer`:
https://canvas-medical.sentry.io/issues/6622885141/events/d8867d6e22614e23a0472cb952455d84/
=> fix: add missing Sentry tags

canvas_sdk/caching/__init__.py
there was a typo in `__all__`, but it's not needed in that file so I removed it entirely.
=> fix: correct a typo

canvas_sdk/tests/caching/test_plugins.py, plugin_runner/sandbox.py, plugin_runner/tests/fixtures/plugins/test_caching_api/CANVAS_MANIFEST.json, plugin_runner/tests/fixtures/plugins/test_caching_api/protocols/my_secondary_protocol.py, plugin_runner/tests/fixtures/plugins/test_caching_api/wrapper.py
https://canvasmedical.atlassian.net/browse/KOALA-2926
@dbajet brought up an issue importing `get_cache` here: https://github.com/canvas-medical/canvas-plugins/issues/619
I wrote a test to verify whether it was the `plugin_only` decorator and could not reproduce the issue.
@jamagalhaes pointed out that the issue with reproducing the issue is that we were mocking `plugin_only`, which hid the failure, and provided the fix. Thank you!
=> fix: allow non-protocol imports, add tests

canvas_sdk/utils/http.py
Internal tracking: [KOALA-2981](https://canvasmedical.atlassian.net/browse/KOALA-2981)
This pull request introduces a new HTTP client, `PharmacyHttp`, to interact with the pharmacy service. It includes methods for searching pharmacies and retrieving pharmacy details by NCPDP ID. Additionally, the `pharmacy_http` instance is added to the module's exports.
* `canvas_sdk/utils/http.py`: Added the `PharmacyHttp` class, which includes:
- [`search_pharmacies`](diffhunk://#diff-5a08695780c2698aa0b5c76219ff9bfef51ec931371d5743c15db57513a82b27R291-R328): A method to search for pharmacies using a search term and optional latitude/longitude parameters.
- [`get_pharmacy_by_ncpdp_id`](diffhunk://#diff-5a08695780c2698aa0b5c76219ff9bfef51ec931371d5743c15db57513a82b27R291-R328): A method to retrieve …
=> feat: expose a pharmacy search view

plugin_runner/sandbox.py, plugin_runner/tests/test_sandbox.py
Adds `vars()` for use by plugins as well as tests that it does not result in a sandbox escape in the same way we test `__dict__`.
=> add vars(), tests, and remove one redundant test

canvas_sdk/v1/data/note.py
Internal tracking: https://canvasmedical.atlassian.net/browse/KOALA-3031
Adds two new models to the data module:
- NoteStateChangeEvent
- Note history
- CurrentNoteStateEvent
- The most recent event in a note's history
=> feat: add note state change event models

.github/workflows/pre-commit-auto-update.yml
The `pre-commit-auto-update` action is scheduled to run nightly and runs on all forks as well. Forks do not have access to `PROJECT_AND_REPO_PAT` (correctly) but this causes the job to fail and email alerts to be sent nightly on every fork
Update workflow to only run on `canvas-medical/canvas-plugins` to reduce the noise
=> chore: do not run auto update action on forks

pyproject.toml, uv.lock
https://canvasmedical.atlassian.net/browse/KOALA-3049
I ran before and after comparisons twice:
119,280 → 128,656 kb = 9,376 kb gain
118,288 → 124,320 kb = 6,032 kb gain
average = 7,704 kb
7.7mb RSS is a little high to support one specific  signing method but I'll leave this PR open for discussion.
this can go in after https://github.com/canvas-medical/canvas-plugins/pull/837, which saves about 2.85x what this costs.
=> feat: add cryptography dependency

canvas_sdk/commands/commands/exam.py, canvas_sdk/commands/commands/questionnaire/__init__.py, canvas_sdk/commands/commands/questionnaire/question.py, canvas_sdk/commands/commands/questionnaire/toggle_questions.py, canvas_sdk/commands/commands/review_of_systems.py, canvas_sdk/commands/commands/structured_assessment.py, canvas_sdk/tests/commands/test_toggle_questions_mixin.py
Internal tracking: [KOALA-2903](https://canvasmedical.atlassian.net/browse/KOALA-2903)
This pull request introduces a new `ToggleQuestionsMixin` class to enhance questionnaire-based commands with functionality for toggling question states. It also updates several command classes to use this mixin and adds comprehensive tests for its behavior. The most important changes include the implementation of the mixin, integration with existing commands, and extensive test coverage.
* [`canvas_sdk/commands/commands/questionnaire/toggle_questions.py`](diffhunk://#diff-896337de07ef1271b01ae2f7a5735be5d370f19867dfc26136e9ddc8bde2ebc4R1-R65): Added the `ToggleQuestionsMixin` class, which provides methods to enable/disable questions, retrieve toggle states, and integrate these states into command …
=> feat: implement question toggles for questionnaire based commands

canvas_sdk/tests/commands/test_toggle_questions_mixin.py, canvas_sdk/tests/data/test_models.py
This pull request refactors the test files `test_toggle_questions_mixin.py` and `test_models.py` to improve type safety, enhance readability, and ensure consistent behavior across tests. The key changes include the use of `pytest` fixtures for test class creation, explicit type casting, and the removal of unnecessary `@patch` decorators.
* Introduced a `pytest.fixture` for creating the `TestCommand` class, ensuring consistent setup and preventing pytest from treating it as a test case.
* Updated all test functions to use explicit type annotations (`ToggleQuestionsMixin`) for improved type safety and readability. [[1]](diffhunk://#diff-b1de6d4853b19281ca8e34650ee982986d7429f0a7dfc6be7a53a9b569790417L68-R81) [[2]](diffhunk://#diff-b1de6d4853b19281ca8e34650ee982986d7429f0a7dfc6be7a53a9b569790 …
=> chore: update question toggle tests to patch the correct method

canvas_cli/apps/plugin/plugin.py
Based on a need surfaced when we had a customer use a virtualenv inside their plugin directory that was not prefixed with a `.`.
Uploading this plugin resulted in a 500 error from the instance when it ran out of memory and was killed.
I used limits of 100 files and 1 megabyte for the warnings.
=> feat: add warnings if many files, large files, or large total size are found

plugin_runner/installation.py
Reagan [ran into](https://canvas-medical.slack.com/archives/C055B74UKJP/p1751374815943519) an issue during local development where he was unable to install plugins but there wasn't a useful error explaining that the plugin download had failed, it was failing at the next step (archive extraction) since the file contained an error message instead of the expected archive.
The root cause was an AWS region mismatch, which affected S3 signature generation.
This change makes it easier to see why a plugin installation failed if the root cause is the download from S3.
=> fix: raise on bad status from S3 in `download_plugin`

plugin_runner/plugin_runner.py
https://canvasmedical.atlassian.net/browse/KOALA-3267
Some plugins send many effects, and the combined payloads exceed the default message size limit for gRPC. This PR increases the limit somewhat but does not allow unlimited payloads.
=> fix: set size maximums for gRPC messages

canvas_cli/apps/run_plugins/run_plugins.py, canvas_cli/apps/run_plugins/tests.py, settings.py
[KOALA-3037](https://canvasmedical.atlassian.net/browse/KOALA-3037)
This pull request introduces significant enhancements to the `canvas_cli` application to improve local plugin development workflows. The changes include adding database reset and seeding capabilities, refining database connection handling, and updating associated tests and configurations. 
* Introduced `_patch_default_db_connection` context manager to temporarily allow database writes by patching the default Django DB connection.
* Added `_reset_db` function to reset the SQLite database, with optional support for running a seed file to initialize the database.
* Refactored `run_plugin` and `run_plugins` to include options for resetting the database and specifying a database setup file. These options are validated to …
=> feat(cli): add local database support to the run-plugin cli command

canvas_sdk/v1/data/__init__.py, canvas_sdk/v1/data/staff.py, plugin_runner/allowed-module-imports.json
INTERNAL TRACKING: https://canvasmedical.atlassian.net/browse/KOALA-3310
This pull request introduces a new `StaffLicense` model to the codebase, which represents licenses and certifications associated with staff members. 
**Addition of Staff License Model:**
* Added a new `StaffLicense` model to `canvas_sdk/v1/data/staff.py`, including fields for license details, issuing authority, dates, and type, and linked to the `Staff` model.
**Exports and Imports:**
* Updated `canvas_sdk/v1/data/__init__.py` to import and export `StaffLicense` so it is available throughout the SDK. [[1]](diffhunk://#diff-7b0c97fc42b6555943e206a71ce18b4e13f011b8a125f11e6983fffe154e3f5bL86-R86) [[2]](diffhunk://#diff-7b0c97fc42b6555943e206a71ce18b4e13f011b8a125f11e6983fffe154e3f5bR186)
**Plugin and Module …
=> feat: staff license
